import { CatDto } from '../dto/cat.dto';
export declare const GENESIS_ROW: {
    id: string;
    catNumber: number;
    txHash: string;
    blockHash: string;
    blockHeight: number;
    mintedAt: Date;
    mintedBy: string;
    fee: number;
    weight: number;
    size: number;
    feeRate: number;
    sat: number;
    value: number;
    category: string;
    genesis: boolean;
    catColors: string[];
    gender: string;
    designIndex: number;
    designPose: string;
    designExpression: string;
    designPattern: string;
    designFacing: string;
    laserEyes: string;
    background: string;
    backgroundColors: string[];
    crown: string;
    glasses: string;
    glassesColors: never[];
    rarityBits: null;
    rarityRank: null;
    rarityCategoryTotal: number;
};
export declare const GENESIS_DTO: CatDto;
